from django.contrib import admin
from first_app.models import (Ekstraklasa, Pierwsza_Liga, Druga_Liga, Hiszpania, Anglia, Wlochy, Niemcy, Francja,Portugalia,Rosja,
Belgia,Ukraina,Holandia,Turcja,Austria,Dania,Szkocja,Czechy,Cypr,Szwajcaria,Grecja,Serbia,Chorwacja,Szwecja,Norwegia,Izrael,
Kazachstan,Bialorus,Azerbejdzan,Bulgaria,Rumunia,Slowacja,Liechtenstein,Slowenia, Wegry,Luxembourg,Litwa,Armenia,Lotwa,Albania,
Macedonia,Bosnia,Moldawia,Irlandia,Finlandia,Gruzja, Malta, Islandia, Walia, Irlandia_Pln, Gibraltar,Czarnogora,Estonia, Kosowo,
Wyspy_Owcze,Andora,San_Marino,    Elim_LM_1,Elim_LM_2,Elim_LM_3,Elim_LM_4,Elim_LE_3,Elim_LE_4, Elim_ECL_1,Elim_ECL_2,Elim_ECL_3,Elim_ECL_4,
LM_group,LE_group,ECL_group,      LM_1_8,LM_cwiercfinal,LM_polfinal,LM_final,LM_winner,LE_1_16,LE_1_8,LE_cwiercfinal,LE_polfinal,LE_final,LE_winner,
ECL_1_16,ECL_1_8,ECL_cwiercfinal,ECL_polfinal,ECL_final,ECL_winner, LM_gallery,LE_gallery,ECL_gallery,POL_gallery,PP_gallery)

# Register your models here.

admin.site.register(Ekstraklasa)
admin.site.register(Pierwsza_Liga)
admin.site.register(Druga_Liga)
admin.site.register(Hiszpania)
admin.site.register(Anglia)
admin.site.register(Wlochy)
admin.site.register(Niemcy)
admin.site.register(Francja)
admin.site.register(Portugalia)
admin.site.register(Rosja)
admin.site.register(Belgia)
admin.site.register(Ukraina)
admin.site.register(Holandia)
admin.site.register(Turcja)
admin.site.register(Austria)
admin.site.register(Dania)
admin.site.register(Szkocja)
admin.site.register(Czechy)
admin.site.register(Cypr)
admin.site.register(Szwajcaria)
admin.site.register(Grecja)
admin.site.register(Serbia)
admin.site.register(Chorwacja)
admin.site.register(Szwecja)
admin.site.register(Norwegia)
admin.site.register(Izrael)
admin.site.register(Kazachstan)
admin.site.register(Bialorus)
admin.site.register(Azerbejdzan)
admin.site.register(Bulgaria)
admin.site.register(Rumunia)
admin.site.register(Slowacja)
admin.site.register(Liechtenstein)
admin.site.register(Slowenia)
admin.site.register(Wegry)
admin.site.register(Luxembourg)
admin.site.register(Litwa)
admin.site.register(Armenia)
admin.site.register(Lotwa)
admin.site.register(Albania)
admin.site.register(Macedonia)
admin.site.register(Bosnia)
admin.site.register(Moldawia)
admin.site.register(Finlandia)
admin.site.register(Irlandia)
admin.site.register(Gruzja)
admin.site.register(Malta)
admin.site.register(Islandia)
admin.site.register(Walia)
admin.site.register(Irlandia_Pln)
admin.site.register(Gibraltar)
admin.site.register(Czarnogora)
admin.site.register(Estonia)
admin.site.register(Kosowo)
admin.site.register(Wyspy_Owcze)
admin.site.register(Andora)
admin.site.register(San_Marino)

admin.site.register(Elim_LM_1)
admin.site.register(Elim_LM_2)
admin.site.register(Elim_LM_3)
admin.site.register(Elim_LM_4)
admin.site.register(Elim_LE_3)
admin.site.register(Elim_LE_4)
admin.site.register(Elim_ECL_1)
admin.site.register(Elim_ECL_2)
admin.site.register(Elim_ECL_3)
admin.site.register(Elim_ECL_4)

admin.site.register(LM_group)
admin.site.register(LE_group)
admin.site.register(ECL_group)

admin.site.register(LM_1_8)
admin.site.register(LM_cwiercfinal)
admin.site.register(LM_polfinal)
admin.site.register(LM_final)
admin.site.register(LM_winner)
admin.site.register(LE_1_16)
admin.site.register(LE_1_8)
admin.site.register(LE_cwiercfinal)
admin.site.register(LE_polfinal)
admin.site.register(LE_final)
admin.site.register(LE_winner)
admin.site.register(ECL_1_16)
admin.site.register(ECL_1_8)
admin.site.register(ECL_cwiercfinal)
admin.site.register(ECL_polfinal)
admin.site.register(ECL_final)
admin.site.register(ECL_winner)

admin.site.register(LM_gallery)
admin.site.register(ECL_gallery)
admin.site.register(LE_gallery)
admin.site.register(POL_gallery)
admin.site.register(PP_gallery)
