from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^europa/$',views.europa,name='europa'),
    url(r'^eliminacje_LM/$',views.eliminacje_LM,name='eliminacje_LM'),
    url(r'^eliminacje_LE/$',views.eliminacje_LE,name='eliminacje_LE'),
    url(r'^eliminacje_ECL/$',views.eliminacje_ECL,name='eliminacje_ECL'),
    url(r'^LM/$',views.LM,name='LM'),
    url(r'^LE/$',views.LE,name='LE'),
    url(r'^ECL/$',views.ECL,name='ECL'),

    url(r'^gallery_europa/$',views.gallery_europa,name='gallery_europa'),
    url(r'^gallery_polska/$',views.gallery_polska,name='gallery_polska'),

    url(r'^ekstraklasa/$',views.ekstraklasa,name='ekstraklasa'),
    url(r'^pier_liga/$',views.pier_liga,name='pier_liga'),
    url(r'^druga_liga/$',views.drug_liga,name='druga_liga'),
    url(r'^puchar/$',views.puchar_polski,name='puchar'),
    url(r'^niemcy/$',views.niemcy,name='niemcy'),
    url(r'^francja/$',views.francja,name='francja'),
    url(r'^hiszpania/$',views.hiszpania,name='hiszpania'),
    url(r'^wlochy/$',views.wlochy,name='wlochy'),
    url(r'^anglia/$',views.anglia,name='anglia'),

    url(r'^portugalia/$',views.portugalia,name='portugalia'),
    url(r'^rosja/$',views.rosja,name='rosja'),
    url(r'^belgia/$',views.belgia,name='belgia'),
    url(r'^ukraina/$',views.ukraina,name='ukraina'),
    url(r'^holandia/$',views.holandia,name='holandia'),
    url(r'^turcja/$',views.turcja,name='turcja'),
    url(r'^austria/$',views.austria,name='austria'),
    url(r'^dania/$',views.dania,name='dania'),
    url(r'^szkocja/$',views.szkocja,name='szkocja'),
    url(r'^czechy/$',views.czechy,name='czechy'),
    url(r'^cypr/$',views.cypr,name='cypr'),
    url(r'^szwajcaria/$',views.szwajcaria,name='szwajcaria'),
    url(r'^grecja/$',views.grecja,name='grecja'),
    url(r'^serbia/$',views.serbia,name='serbia'),
    url(r'^chorwacja/$',views.chorwacja,name='chorwacja'),
    url(r'^szwecja/$',views.szwecja,name='szwecja'),
    url(r'^norwegia/$',views.norwegia,name='norwegia'),
    url(r'^izrael/$',views.izrael,name='izrael'),
    url(r'^kazachstan/$',views.kazachstan,name='kazachstan'),
    url(r'^bialorus/$',views.bialorus,name='bialorus'),
    url(r'^azerbejdzan/$',views.azerbejdzan,name='azerbejdzan'),
    url(r'^bulgaria/$',views.bulgaria,name='bulgaria'),
    url(r'^rumunia/$',views.rumunia,name='rumunia'),
    url(r'^slowacja/$',views.slowacja,name='slowacja'),
    url(r'^liechtenstein/$',views.liechtenstein,name='liechtenstein'),
    url(r'^slowenia/$',views.slowenia,name='slowenia'),
    url(r'^wegry/$',views.wegry,name='wegry'),
    url(r'^luxembourg/$',views.luxembourg,name='luxembourg'),
    url(r'^litwa/$',views.litwa,name='litwa'),
    url(r'^armenia/$',views.armenia,name='armenia'),
    url(r'^lotwa/$',views.lotwa,name='lotwa'),
    url(r'^albania/$',views.albania,name='albania'),
    url(r'^macedonia/$',views.macedonia,name='macedonia'),
    url(r'^bosnia/$',views.bosnia,name='bosnia'),
    url(r'^moldawia/$',views.moldawia,name='moldawia'),
    url(r'^finlandia/$',views.finlandia,name='finlandia'),
    url(r'^irlandia/$',views.irlandia,name='irlandia'),
    url(r'^gruzja/$',views.gruzja,name='gruzja'),
    url(r'^malta/$',views.malta,name='malta'),
    url(r'^islandia/$',views.islandia,name='islandia'),
    url(r'^walia/$',views.walia,name='walia'),
    url(r'^irlandia_Pln/$',views.irlandia_Pln,name='irlandia_Pln'),
    url(r'^gibraltar/$',views.gibraltar,name='gibraltar'),
    url(r'^czarnogora/$',views.czarnogora,name='czarnogora'),
    url(r'^estonia/$',views.estonia,name='estonia'),
    url(r'^kosowo/$',views.kosowo,name='kosowo'),
    url(r'^wyspy_Owcze/$',views.wyspy_Owcze,name='wyspy_Owcze'),
    url(r'^andora/$',views.andora,name='andora'),
    url(r'^san_Marino/$',views.san_Marino,name='san_Marino'),
]
