# Generated by Django 3.1.5 on 2021-03-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20210320_1502'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Ekstraklasa',
        ),
        migrations.DeleteModel(
            name='Liga16',
        ),
    ]
