# Generated by Django 3.1.5 on 2021-03-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20210320_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstraklasa',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ekstraklasa',
            name='conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ekstraklasa',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ekstraklasa',
            name='scored',
            field=models.IntegerField(default=0),
        ),
    ]
