# Generated by Django 3.1.5 on 2021-03-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_pierwsza_liga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
