# Generated by Django 3.1.5 on 2021-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_druga_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='druga_liga',
            name='last_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='druga_liga',
            name='last_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekstraklasa',
            name='last_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ekstraklasa',
            name='last_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pierwsza_liga',
            name='last_conceded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pierwsza_liga',
            name='last_scored',
            field=models.IntegerField(default=0),
        ),
    ]
