# Generated by Django 3.1.5 on 2021-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20210325_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='anglia',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='druga_liga',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='francja',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='hiszpania',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='niemcy',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='pierwsza_liga',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
        migrations.AddField(
            model_name='wlochy',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
    ]
