# Generated by Django 3.1.5 on 2021-03-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_albania_andora_armenia_austria_azerbejdzan_belgia_bialorus_bosnia_bulgaria_chorwacja_cypr_czarnogora'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slovenia',
            new_name='Slowenia',
        ),
    ]
