# Generated by Django 3.1.5 on 2021-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_elim_ecl_1_elim_ecl_1_wyniki_elim_ecl_2_elim_ecl_2_wyniki_elim_ecl_3_elim_ecl_3_wyniki_elim_ecl_4_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elim_ecl_1_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_ecl_2_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_ecl_3_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_ecl_4_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_le_3_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_le_4_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_lm_1_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_lm_2_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_lm_3_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='elim_lm_4_wyniki',
            name='result',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
