# Generated by Django 3.1.5 on 2021-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_auto_20210329_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elim_lm_1_wyniki',
            name='result',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
