# Generated by Django 3.1.5 on 2021-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0026_auto_20210330_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECL_1_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ECL_cwiercfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ECL_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ECL_polfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ECL_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_1_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_cwiercfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_polfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LM_1_8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LM_cwiercfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LM_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LM_polfinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LM_winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
    ]
