# Generated by Django 3.1.5 on 2021-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_ecl_1_8_ecl_cwiercfinal_ecl_final_ecl_polfinal_ecl_winner_le_1_8_le_cwiercfinal_le_final_le_polfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecl_1_8',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ecl_cwiercfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ecl_polfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='le_1_8',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='le_cwiercfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='le_polfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lm_1_8',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lm_cwiercfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lm_polfinal',
            name='last_scored_2',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
