# Generated by Django 3.1.5 on 2021-03-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0028_auto_20210331_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECL_1_16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('last_scored_2', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LE_1_16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('strength', models.IntegerField(default=2000)),
                ('image', models.ImageField(upload_to='upload/')),
                ('last_scored', models.CharField(blank=True, default='', max_length=10)),
                ('last_scored_2', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='()', max_length=264)),
            ],
        ),
    ]
