# Generated by Django 3.1.5 on 2021-04-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0030_auto_20210401_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstraklasa',
            name='country',
            field=models.CharField(default='()', max_length=264),
        ),
    ]
